name: Build and Release APK

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # Replace with your Flutter version

      - name: Navigate to app directory
        working-directory: compass_app/app
        run: flutter pub get

      - name: Build APK
        working-directory: compass_app/app
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: compass_app/app/build/app/outputs/flutter-apk/app-release.apk
